"""Report repository for database operations on the reports table."""

import logging
from typing import Optional

from database.connection import get_db
from app.Models.report import Report

logger = logging.getLogger(__name__)


class ReportRepository:
    """Repository handling all CRUD operations for Report entities."""

    def save(self, report: Report) -> Report:
        """Save a new report to the database.

        Args:
            report: The Report object to persist.

        Returns:
            The persisted Report object with generated ID.
        """
        with get_db() as db:
            db.add(report)
            db.flush()
            db.expunge(report)
            logger.info(
                "Rapport sauvegardé: ID=%d, format='%s'", report.id, report.format
            )
            return report

    def find_by_user(self, user_id: int) -> list[Report]:
        """Find all reports generated by a specific user.

        Args:
            user_id: The user's ID.

        Returns:
            A list of Report objects belonging to the user.
        """
        with get_db() as db:
            reports = (
                db.query(Report)
                .filter(Report.user_id == user_id)
                .order_by(Report.genere_le.desc())
                .all()
            )
            for r in reports:
                db.expunge(r)
            return reports

    def find_by_id(self, report_id: int) -> Optional[Report]:
        """Find a report by its primary key.

        Args:
            report_id: The report's ID.

        Returns:
            The Report object or None if not found.
        """
        with get_db() as db:
            report = db.query(Report).filter(Report.id == report_id).first()
            if report:
                db.expunge(report)
            return report

    def find_all(self) -> list[Report]:
        """Retrieve all reports from the database.

        Returns:
            A list of all Report objects.
        """
        with get_db() as db:
            reports = db.query(Report).order_by(Report.genere_le.desc()).all()
            for r in reports:
                db.expunge(r)
            return reports

    def delete(self, report_id: int) -> bool:
        """Delete a report from the database.

        Args:
            report_id: The report's ID.

        Returns:
            True if deleted, False if not found.
        """
        with get_db() as db:
            report = db.query(Report).filter(Report.id == report_id).first()
            if not report:
                logger.warning("Rapport non trouvé pour suppression: ID=%d", report_id)
                return False
            db.delete(report)
            logger.info("Rapport supprimé: ID=%d", report_id)
            return True
